### ISSUE TITLE
Hard coded oAuth token

### ISSUE THREAD

**Issue by skyline-gleb** [rseek/stf-connect#2]
Maybe move oauth_token in spec.json?

**Comment by skyline-gleb** [comment]
And STF host too.

**Comment by rseek** [comment]
`spec.json` is supposed to be special JSON only for defining devices needed.
Maybe I will add `config.json` (as config file for connector.py "app") and add oauth_token and host there.

`spec.json` задумывался как JSON специально для отбора нужных девайсов,
наверное я добавлю `config.json` (как конфиг именно для скрипта connector.py) и туда уже добавлю все эти параметры

**Comment by rseek** [comment]
done

https://github.com/rseek/stf-connect/commit/28d0aaec8f06693d54656513a715848e155dd343
